development:
  adapter: postgresql
  encoding: unicode
  database: startopensource_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: startopensource_test
  pool: 5
  username:
  password:

